### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/dolman#10]
@dheavy the API needs to be discussed. For the time being, we have the following:

``` js
var express = require('express'),
      dolman = require('dolman');

var something = dolman(express, options);

// Create a router from a controllers' array
var router = something.router(controller);
```

This feels a bit clunky and I am sure we can do better.

**Comment by dheavy** [comment]
@Yomguithereal But should we? This API reads very swiftly if you come from a conventional **express** or **backbone/marionette** router background. It also looks and feels like a wrapper just when you look at the code, and that's perfect for quick adoption.
Though exposing the method for methods à la `addRoute(route:Object)` or one-liners would be sweet too IMHO:

``` javascript
// Ridiculous, but you get the idea.
var api = require('dolman')(require('express'), require('./opts'), require('./controllers'));  
api.readyToDoSomethingOnLine2();
```

Or maybe you're already leaning towards a specific vision?

**Comment by Yomguithereal** [comment]
The real question here would probably be: should we wrap the express dependency or rather the application itself (would only be possible if the app is able to access the original express dependency which I don't recall).

**Comment by Yomguithereal** [comment]
Or even? Shouldn't dolman wrapping create the express app:

``` js
var express = require('express'),
      dolman = require('dolman');

var app = dolman(express, options);

// app would be the express app but enhanced?
// Could lead to confusion somewhat because the router would not be the same on express and on app.
```

**Comment by dheavy** [comment]
Dolman wrapping... I don't know. Are you ready to proxy all of Express' API? Because that's what I would expect in such a case. Otherwise Dolman would be much more than a smart, thin, wrapper. It'd be a new framework, like Strongloop.
I'm not arguing against the proxying though. The promise of an enhanced Express app is great: almost no learning curve and full of quick wins... as long as I can use at least 90% of the API I'm used to. It'd feel **almost** like a plug'n'play layer of niceties.

e.g. Could I still `app.use(<somemiddleware>)`? Would I expect a quick "upgrade from a regular express app" documentation in such a configuration?

**Comment by dheavy** [comment]
On a second thought and to remove the ambiguity: I'm pro wrapping/replacing the express app.

**Comment by Yomguithereal** [comment]
By wrapping/replacing the app I was merely speaking about something of the kind:

``` js
function dolman(express) {
  var app = express();

  // Add something
  app.something = function() {};

  return app;
}

// So you would handle a real express app, not some kind of proxy over it.
app.use(whatever);
```

**Comment by Yomguithereal** [comment]
One of the potential pattern would also be to expose a factory like some libraries do:

``` js
var express = require('express'),
      dolman = require('dolman')(express, opts);

var app = express();

var firstRouter = dolman.router(something);

app.use('/whatever', firstRouter);
```

**Comment by dheavy** [comment]
+1
Much better.

**Comment by Yomguithereal** [comment]
What's fun is that this is exactly the same as the first one proposed :smile:.

**Comment by dheavy** [comment]
hahaha classic already-agreeing-people argument
