### ISSUE TITLE
Specify required middlewares for each router, not globally

### ISSUE THREAD

**Issue by jlesceau** [Yomguithereal/dolman#19]
`app.use(middleware, router)` will result in every router passed to express after will use this middleware

**Comment by Yomguithereal** [comment]
So we have two solutions here:

``` js
// 1.
dolman.router(routes, {before: [middlewares]});

// 2.
dolman.router([middlewares], routes);
```

**Comment by jlesceau** [comment]
Does it mean you could have:

```
// 1.
dolman.router(routes, {before: [middlewares], after: [moreMiddlewares]});

// 2.
dolman.router([middlewares], routes, [moreMiddlewares]);
```

?

**Comment by Yomguithereal** [comment]
This yes:

``` js
// 1.
dolman.router(routes, {before: [middlewares], after: [moreMiddlewares]});
```

This no:

``` js
// 2.
dolman.router([middlewares], routes, [moreMiddlewares]);
```

Before and after actually mean before and after validation.

**Comment by dheavy** [comment]
Looks a lot like issue #4.

Also, I'd advocate for proposition 1.

**Comment by jacomyal** [comment]
Solution 1, with a default behaviour settable in the options, to let the possibility to use `dolman.router(routes, [middlewares])` ?
